// source: builder/v1/builder.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.boxygen.builder.v1.AddRequest', null, global);
goog.exportSymbol('proto.boxygen.builder.v1.CommitRequest', null, global);
goog.exportSymbol('proto.boxygen.builder.v1.ConfigRequest', null, global);
goog.exportSymbol('proto.boxygen.builder.v1.Container', null, global);
goog.exportSymbol('proto.boxygen.builder.v1.CopyRequest', null, global);
goog.exportSymbol('proto.boxygen.builder.v1.FromRequest', null, global);
goog.exportSymbol('proto.boxygen.builder.v1.FromResponse', null, global);
goog.exportSymbol('proto.boxygen.builder.v1.OutputResponse', null, global);
goog.exportSymbol('proto.boxygen.builder.v1.RunRequest', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.boxygen.builder.v1.Container = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.boxygen.builder.v1.Container, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.boxygen.builder.v1.Container.displayName = 'proto.boxygen.builder.v1.Container';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.boxygen.builder.v1.OutputResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.boxygen.builder.v1.OutputResponse.repeatedFields_, null);
};
goog.inherits(proto.boxygen.builder.v1.OutputResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.boxygen.builder.v1.OutputResponse.displayName = 'proto.boxygen.builder.v1.OutputResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.boxygen.builder.v1.AddRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.boxygen.builder.v1.AddRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.boxygen.builder.v1.AddRequest.displayName = 'proto.boxygen.builder.v1.AddRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.boxygen.builder.v1.CommitRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.boxygen.builder.v1.CommitRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.boxygen.builder.v1.CommitRequest.displayName = 'proto.boxygen.builder.v1.CommitRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.boxygen.builder.v1.ConfigRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.boxygen.builder.v1.ConfigRequest.repeatedFields_, null);
};
goog.inherits(proto.boxygen.builder.v1.ConfigRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.boxygen.builder.v1.ConfigRequest.displayName = 'proto.boxygen.builder.v1.ConfigRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.boxygen.builder.v1.CopyRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.boxygen.builder.v1.CopyRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.boxygen.builder.v1.CopyRequest.displayName = 'proto.boxygen.builder.v1.CopyRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.boxygen.builder.v1.FromRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.boxygen.builder.v1.FromRequest.repeatedFields_, null);
};
goog.inherits(proto.boxygen.builder.v1.FromRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.boxygen.builder.v1.FromRequest.displayName = 'proto.boxygen.builder.v1.FromRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.boxygen.builder.v1.FromResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.boxygen.builder.v1.FromResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.boxygen.builder.v1.FromResponse.displayName = 'proto.boxygen.builder.v1.FromResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.boxygen.builder.v1.RunRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.boxygen.builder.v1.RunRequest.repeatedFields_, null);
};
goog.inherits(proto.boxygen.builder.v1.RunRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.boxygen.builder.v1.RunRequest.displayName = 'proto.boxygen.builder.v1.RunRequest';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.boxygen.builder.v1.Container.prototype.toObject = function(opt_includeInstance) {
  return proto.boxygen.builder.v1.Container.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.boxygen.builder.v1.Container} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.boxygen.builder.v1.Container.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.boxygen.builder.v1.Container}
 */
proto.boxygen.builder.v1.Container.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.boxygen.builder.v1.Container;
  return proto.boxygen.builder.v1.Container.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.boxygen.builder.v1.Container} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.boxygen.builder.v1.Container}
 */
proto.boxygen.builder.v1.Container.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.boxygen.builder.v1.Container.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.boxygen.builder.v1.Container.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.boxygen.builder.v1.Container} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.boxygen.builder.v1.Container.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.boxygen.builder.v1.Container.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.boxygen.builder.v1.Container} returns this
 */
proto.boxygen.builder.v1.Container.prototype.setId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.boxygen.builder.v1.OutputResponse.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.boxygen.builder.v1.OutputResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.boxygen.builder.v1.OutputResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.boxygen.builder.v1.OutputResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.boxygen.builder.v1.OutputResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    logList: (f = jspb.Message.getRepeatedField(msg, 1)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.boxygen.builder.v1.OutputResponse}
 */
proto.boxygen.builder.v1.OutputResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.boxygen.builder.v1.OutputResponse;
  return proto.boxygen.builder.v1.OutputResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.boxygen.builder.v1.OutputResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.boxygen.builder.v1.OutputResponse}
 */
proto.boxygen.builder.v1.OutputResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.addLog(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.boxygen.builder.v1.OutputResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.boxygen.builder.v1.OutputResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.boxygen.builder.v1.OutputResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.boxygen.builder.v1.OutputResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getLogList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      1,
      f
    );
  }
};


/**
 * repeated string log = 1;
 * @return {!Array<string>}
 */
proto.boxygen.builder.v1.OutputResponse.prototype.getLogList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 1));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.boxygen.builder.v1.OutputResponse} returns this
 */
proto.boxygen.builder.v1.OutputResponse.prototype.setLogList = function(value) {
  return jspb.Message.setField(this, 1, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.boxygen.builder.v1.OutputResponse} returns this
 */
proto.boxygen.builder.v1.OutputResponse.prototype.addLog = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 1, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.boxygen.builder.v1.OutputResponse} returns this
 */
proto.boxygen.builder.v1.OutputResponse.prototype.clearLogList = function() {
  return this.setLogList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.boxygen.builder.v1.AddRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.boxygen.builder.v1.AddRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.boxygen.builder.v1.AddRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.boxygen.builder.v1.AddRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    container: (f = msg.getContainer()) && proto.boxygen.builder.v1.Container.toObject(includeInstance, f),
    src: jspb.Message.getFieldWithDefault(msg, 2, ""),
    dest: jspb.Message.getFieldWithDefault(msg, 3, ""),
    from: jspb.Message.getFieldWithDefault(msg, 10, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.boxygen.builder.v1.AddRequest}
 */
proto.boxygen.builder.v1.AddRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.boxygen.builder.v1.AddRequest;
  return proto.boxygen.builder.v1.AddRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.boxygen.builder.v1.AddRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.boxygen.builder.v1.AddRequest}
 */
proto.boxygen.builder.v1.AddRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.boxygen.builder.v1.Container;
      reader.readMessage(value,proto.boxygen.builder.v1.Container.deserializeBinaryFromReader);
      msg.setContainer(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setSrc(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setDest(value);
      break;
    case 10:
      var value = /** @type {string} */ (reader.readString());
      msg.setFrom(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.boxygen.builder.v1.AddRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.boxygen.builder.v1.AddRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.boxygen.builder.v1.AddRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.boxygen.builder.v1.AddRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getContainer();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.boxygen.builder.v1.Container.serializeBinaryToWriter
    );
  }
  f = message.getSrc();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getDest();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getFrom();
  if (f.length > 0) {
    writer.writeString(
      10,
      f
    );
  }
};


/**
 * optional Container container = 1;
 * @return {?proto.boxygen.builder.v1.Container}
 */
proto.boxygen.builder.v1.AddRequest.prototype.getContainer = function() {
  return /** @type{?proto.boxygen.builder.v1.Container} */ (
    jspb.Message.getWrapperField(this, proto.boxygen.builder.v1.Container, 1));
};


/**
 * @param {?proto.boxygen.builder.v1.Container|undefined} value
 * @return {!proto.boxygen.builder.v1.AddRequest} returns this
*/
proto.boxygen.builder.v1.AddRequest.prototype.setContainer = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.boxygen.builder.v1.AddRequest} returns this
 */
proto.boxygen.builder.v1.AddRequest.prototype.clearContainer = function() {
  return this.setContainer(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.boxygen.builder.v1.AddRequest.prototype.hasContainer = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string src = 2;
 * @return {string}
 */
proto.boxygen.builder.v1.AddRequest.prototype.getSrc = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.boxygen.builder.v1.AddRequest} returns this
 */
proto.boxygen.builder.v1.AddRequest.prototype.setSrc = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string dest = 3;
 * @return {string}
 */
proto.boxygen.builder.v1.AddRequest.prototype.getDest = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.boxygen.builder.v1.AddRequest} returns this
 */
proto.boxygen.builder.v1.AddRequest.prototype.setDest = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string from = 10;
 * @return {string}
 */
proto.boxygen.builder.v1.AddRequest.prototype.getFrom = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 10, ""));
};


/**
 * @param {string} value
 * @return {!proto.boxygen.builder.v1.AddRequest} returns this
 */
proto.boxygen.builder.v1.AddRequest.prototype.setFrom = function(value) {
  return jspb.Message.setProto3StringField(this, 10, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.boxygen.builder.v1.CommitRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.boxygen.builder.v1.CommitRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.boxygen.builder.v1.CommitRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.boxygen.builder.v1.CommitRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    container: (f = msg.getContainer()) && proto.boxygen.builder.v1.Container.toObject(includeInstance, f),
    tag: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.boxygen.builder.v1.CommitRequest}
 */
proto.boxygen.builder.v1.CommitRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.boxygen.builder.v1.CommitRequest;
  return proto.boxygen.builder.v1.CommitRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.boxygen.builder.v1.CommitRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.boxygen.builder.v1.CommitRequest}
 */
proto.boxygen.builder.v1.CommitRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.boxygen.builder.v1.Container;
      reader.readMessage(value,proto.boxygen.builder.v1.Container.deserializeBinaryFromReader);
      msg.setContainer(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setTag(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.boxygen.builder.v1.CommitRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.boxygen.builder.v1.CommitRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.boxygen.builder.v1.CommitRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.boxygen.builder.v1.CommitRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getContainer();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.boxygen.builder.v1.Container.serializeBinaryToWriter
    );
  }
  f = message.getTag();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional Container container = 1;
 * @return {?proto.boxygen.builder.v1.Container}
 */
proto.boxygen.builder.v1.CommitRequest.prototype.getContainer = function() {
  return /** @type{?proto.boxygen.builder.v1.Container} */ (
    jspb.Message.getWrapperField(this, proto.boxygen.builder.v1.Container, 1));
};


/**
 * @param {?proto.boxygen.builder.v1.Container|undefined} value
 * @return {!proto.boxygen.builder.v1.CommitRequest} returns this
*/
proto.boxygen.builder.v1.CommitRequest.prototype.setContainer = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.boxygen.builder.v1.CommitRequest} returns this
 */
proto.boxygen.builder.v1.CommitRequest.prototype.clearContainer = function() {
  return this.setContainer(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.boxygen.builder.v1.CommitRequest.prototype.hasContainer = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string tag = 2;
 * @return {string}
 */
proto.boxygen.builder.v1.CommitRequest.prototype.getTag = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.boxygen.builder.v1.CommitRequest} returns this
 */
proto.boxygen.builder.v1.CommitRequest.prototype.setTag = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.boxygen.builder.v1.ConfigRequest.repeatedFields_ = [10,11,15,16];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.boxygen.builder.v1.ConfigRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.boxygen.builder.v1.ConfigRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.boxygen.builder.v1.ConfigRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.boxygen.builder.v1.ConfigRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    container: (f = msg.getContainer()) && proto.boxygen.builder.v1.Container.toObject(includeInstance, f),
    entrypointList: (f = jspb.Message.getRepeatedField(msg, 10)) == null ? undefined : f,
    cmdList: (f = jspb.Message.getRepeatedField(msg, 11)) == null ? undefined : f,
    workingDir: jspb.Message.getFieldWithDefault(msg, 12, ""),
    user: jspb.Message.getFieldWithDefault(msg, 13, ""),
    envMap: (f = msg.getEnvMap()) ? f.toObject(includeInstance, undefined) : [],
    portsList: (f = jspb.Message.getRepeatedField(msg, 15)) == null ? undefined : f,
    volumesList: (f = jspb.Message.getRepeatedField(msg, 16)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.boxygen.builder.v1.ConfigRequest}
 */
proto.boxygen.builder.v1.ConfigRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.boxygen.builder.v1.ConfigRequest;
  return proto.boxygen.builder.v1.ConfigRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.boxygen.builder.v1.ConfigRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.boxygen.builder.v1.ConfigRequest}
 */
proto.boxygen.builder.v1.ConfigRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.boxygen.builder.v1.Container;
      reader.readMessage(value,proto.boxygen.builder.v1.Container.deserializeBinaryFromReader);
      msg.setContainer(value);
      break;
    case 10:
      var value = /** @type {string} */ (reader.readString());
      msg.addEntrypoint(value);
      break;
    case 11:
      var value = /** @type {string} */ (reader.readString());
      msg.addCmd(value);
      break;
    case 12:
      var value = /** @type {string} */ (reader.readString());
      msg.setWorkingDir(value);
      break;
    case 13:
      var value = /** @type {string} */ (reader.readString());
      msg.setUser(value);
      break;
    case 14:
      var value = msg.getEnvMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readString, null, "", "");
         });
      break;
    case 15:
      var values = /** @type {!Array<number>} */ (reader.isDelimited() ? reader.readPackedInt32() : [reader.readInt32()]);
      for (var i = 0; i < values.length; i++) {
        msg.addPorts(values[i]);
      }
      break;
    case 16:
      var value = /** @type {string} */ (reader.readString());
      msg.addVolumes(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.boxygen.builder.v1.ConfigRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.boxygen.builder.v1.ConfigRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.boxygen.builder.v1.ConfigRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.boxygen.builder.v1.ConfigRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getContainer();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.boxygen.builder.v1.Container.serializeBinaryToWriter
    );
  }
  f = message.getEntrypointList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      10,
      f
    );
  }
  f = message.getCmdList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      11,
      f
    );
  }
  f = message.getWorkingDir();
  if (f.length > 0) {
    writer.writeString(
      12,
      f
    );
  }
  f = message.getUser();
  if (f.length > 0) {
    writer.writeString(
      13,
      f
    );
  }
  f = message.getEnvMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(14, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeString);
  }
  f = message.getPortsList();
  if (f.length > 0) {
    writer.writePackedInt32(
      15,
      f
    );
  }
  f = message.getVolumesList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      16,
      f
    );
  }
};


/**
 * optional Container container = 1;
 * @return {?proto.boxygen.builder.v1.Container}
 */
proto.boxygen.builder.v1.ConfigRequest.prototype.getContainer = function() {
  return /** @type{?proto.boxygen.builder.v1.Container} */ (
    jspb.Message.getWrapperField(this, proto.boxygen.builder.v1.Container, 1));
};


/**
 * @param {?proto.boxygen.builder.v1.Container|undefined} value
 * @return {!proto.boxygen.builder.v1.ConfigRequest} returns this
*/
proto.boxygen.builder.v1.ConfigRequest.prototype.setContainer = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.boxygen.builder.v1.ConfigRequest} returns this
 */
proto.boxygen.builder.v1.ConfigRequest.prototype.clearContainer = function() {
  return this.setContainer(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.boxygen.builder.v1.ConfigRequest.prototype.hasContainer = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * repeated string entrypoint = 10;
 * @return {!Array<string>}
 */
proto.boxygen.builder.v1.ConfigRequest.prototype.getEntrypointList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 10));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.boxygen.builder.v1.ConfigRequest} returns this
 */
proto.boxygen.builder.v1.ConfigRequest.prototype.setEntrypointList = function(value) {
  return jspb.Message.setField(this, 10, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.boxygen.builder.v1.ConfigRequest} returns this
 */
proto.boxygen.builder.v1.ConfigRequest.prototype.addEntrypoint = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 10, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.boxygen.builder.v1.ConfigRequest} returns this
 */
proto.boxygen.builder.v1.ConfigRequest.prototype.clearEntrypointList = function() {
  return this.setEntrypointList([]);
};


/**
 * repeated string cmd = 11;
 * @return {!Array<string>}
 */
proto.boxygen.builder.v1.ConfigRequest.prototype.getCmdList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 11));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.boxygen.builder.v1.ConfigRequest} returns this
 */
proto.boxygen.builder.v1.ConfigRequest.prototype.setCmdList = function(value) {
  return jspb.Message.setField(this, 11, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.boxygen.builder.v1.ConfigRequest} returns this
 */
proto.boxygen.builder.v1.ConfigRequest.prototype.addCmd = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 11, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.boxygen.builder.v1.ConfigRequest} returns this
 */
proto.boxygen.builder.v1.ConfigRequest.prototype.clearCmdList = function() {
  return this.setCmdList([]);
};


/**
 * optional string working_dir = 12;
 * @return {string}
 */
proto.boxygen.builder.v1.ConfigRequest.prototype.getWorkingDir = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 12, ""));
};


/**
 * @param {string} value
 * @return {!proto.boxygen.builder.v1.ConfigRequest} returns this
 */
proto.boxygen.builder.v1.ConfigRequest.prototype.setWorkingDir = function(value) {
  return jspb.Message.setProto3StringField(this, 12, value);
};


/**
 * optional string user = 13;
 * @return {string}
 */
proto.boxygen.builder.v1.ConfigRequest.prototype.getUser = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 13, ""));
};


/**
 * @param {string} value
 * @return {!proto.boxygen.builder.v1.ConfigRequest} returns this
 */
proto.boxygen.builder.v1.ConfigRequest.prototype.setUser = function(value) {
  return jspb.Message.setProto3StringField(this, 13, value);
};


/**
 * map<string, string> env = 14;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,string>}
 */
proto.boxygen.builder.v1.ConfigRequest.prototype.getEnvMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,string>} */ (
      jspb.Message.getMapField(this, 14, opt_noLazyCreate,
      null));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.boxygen.builder.v1.ConfigRequest} returns this
 */
proto.boxygen.builder.v1.ConfigRequest.prototype.clearEnvMap = function() {
  this.getEnvMap().clear();
  return this;};


/**
 * repeated int32 ports = 15;
 * @return {!Array<number>}
 */
proto.boxygen.builder.v1.ConfigRequest.prototype.getPortsList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 15));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.boxygen.builder.v1.ConfigRequest} returns this
 */
proto.boxygen.builder.v1.ConfigRequest.prototype.setPortsList = function(value) {
  return jspb.Message.setField(this, 15, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.boxygen.builder.v1.ConfigRequest} returns this
 */
proto.boxygen.builder.v1.ConfigRequest.prototype.addPorts = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 15, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.boxygen.builder.v1.ConfigRequest} returns this
 */
proto.boxygen.builder.v1.ConfigRequest.prototype.clearPortsList = function() {
  return this.setPortsList([]);
};


/**
 * repeated string volumes = 16;
 * @return {!Array<string>}
 */
proto.boxygen.builder.v1.ConfigRequest.prototype.getVolumesList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 16));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.boxygen.builder.v1.ConfigRequest} returns this
 */
proto.boxygen.builder.v1.ConfigRequest.prototype.setVolumesList = function(value) {
  return jspb.Message.setField(this, 16, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.boxygen.builder.v1.ConfigRequest} returns this
 */
proto.boxygen.builder.v1.ConfigRequest.prototype.addVolumes = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 16, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.boxygen.builder.v1.ConfigRequest} returns this
 */
proto.boxygen.builder.v1.ConfigRequest.prototype.clearVolumesList = function() {
  return this.setVolumesList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.boxygen.builder.v1.CopyRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.boxygen.builder.v1.CopyRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.boxygen.builder.v1.CopyRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.boxygen.builder.v1.CopyRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    container: (f = msg.getContainer()) && proto.boxygen.builder.v1.Container.toObject(includeInstance, f),
    source: jspb.Message.getFieldWithDefault(msg, 2, ""),
    dest: jspb.Message.getFieldWithDefault(msg, 3, ""),
    from: jspb.Message.getFieldWithDefault(msg, 10, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.boxygen.builder.v1.CopyRequest}
 */
proto.boxygen.builder.v1.CopyRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.boxygen.builder.v1.CopyRequest;
  return proto.boxygen.builder.v1.CopyRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.boxygen.builder.v1.CopyRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.boxygen.builder.v1.CopyRequest}
 */
proto.boxygen.builder.v1.CopyRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.boxygen.builder.v1.Container;
      reader.readMessage(value,proto.boxygen.builder.v1.Container.deserializeBinaryFromReader);
      msg.setContainer(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setSource(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setDest(value);
      break;
    case 10:
      var value = /** @type {string} */ (reader.readString());
      msg.setFrom(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.boxygen.builder.v1.CopyRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.boxygen.builder.v1.CopyRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.boxygen.builder.v1.CopyRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.boxygen.builder.v1.CopyRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getContainer();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.boxygen.builder.v1.Container.serializeBinaryToWriter
    );
  }
  f = message.getSource();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getDest();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getFrom();
  if (f.length > 0) {
    writer.writeString(
      10,
      f
    );
  }
};


/**
 * optional Container container = 1;
 * @return {?proto.boxygen.builder.v1.Container}
 */
proto.boxygen.builder.v1.CopyRequest.prototype.getContainer = function() {
  return /** @type{?proto.boxygen.builder.v1.Container} */ (
    jspb.Message.getWrapperField(this, proto.boxygen.builder.v1.Container, 1));
};


/**
 * @param {?proto.boxygen.builder.v1.Container|undefined} value
 * @return {!proto.boxygen.builder.v1.CopyRequest} returns this
*/
proto.boxygen.builder.v1.CopyRequest.prototype.setContainer = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.boxygen.builder.v1.CopyRequest} returns this
 */
proto.boxygen.builder.v1.CopyRequest.prototype.clearContainer = function() {
  return this.setContainer(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.boxygen.builder.v1.CopyRequest.prototype.hasContainer = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string source = 2;
 * @return {string}
 */
proto.boxygen.builder.v1.CopyRequest.prototype.getSource = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.boxygen.builder.v1.CopyRequest} returns this
 */
proto.boxygen.builder.v1.CopyRequest.prototype.setSource = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string dest = 3;
 * @return {string}
 */
proto.boxygen.builder.v1.CopyRequest.prototype.getDest = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.boxygen.builder.v1.CopyRequest} returns this
 */
proto.boxygen.builder.v1.CopyRequest.prototype.setDest = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string from = 10;
 * @return {string}
 */
proto.boxygen.builder.v1.CopyRequest.prototype.getFrom = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 10, ""));
};


/**
 * @param {string} value
 * @return {!proto.boxygen.builder.v1.CopyRequest} returns this
 */
proto.boxygen.builder.v1.CopyRequest.prototype.setFrom = function(value) {
  return jspb.Message.setProto3StringField(this, 10, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.boxygen.builder.v1.FromRequest.repeatedFields_ = [11];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.boxygen.builder.v1.FromRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.boxygen.builder.v1.FromRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.boxygen.builder.v1.FromRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.boxygen.builder.v1.FromRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    image: jspb.Message.getFieldWithDefault(msg, 1, ""),
    as: jspb.Message.getFieldWithDefault(msg, 10, ""),
    ignoreList: (f = jspb.Message.getRepeatedField(msg, 11)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.boxygen.builder.v1.FromRequest}
 */
proto.boxygen.builder.v1.FromRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.boxygen.builder.v1.FromRequest;
  return proto.boxygen.builder.v1.FromRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.boxygen.builder.v1.FromRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.boxygen.builder.v1.FromRequest}
 */
proto.boxygen.builder.v1.FromRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setImage(value);
      break;
    case 10:
      var value = /** @type {string} */ (reader.readString());
      msg.setAs(value);
      break;
    case 11:
      var value = /** @type {string} */ (reader.readString());
      msg.addIgnore(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.boxygen.builder.v1.FromRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.boxygen.builder.v1.FromRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.boxygen.builder.v1.FromRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.boxygen.builder.v1.FromRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getImage();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getAs();
  if (f.length > 0) {
    writer.writeString(
      10,
      f
    );
  }
  f = message.getIgnoreList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      11,
      f
    );
  }
};


/**
 * optional string image = 1;
 * @return {string}
 */
proto.boxygen.builder.v1.FromRequest.prototype.getImage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.boxygen.builder.v1.FromRequest} returns this
 */
proto.boxygen.builder.v1.FromRequest.prototype.setImage = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string as = 10;
 * @return {string}
 */
proto.boxygen.builder.v1.FromRequest.prototype.getAs = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 10, ""));
};


/**
 * @param {string} value
 * @return {!proto.boxygen.builder.v1.FromRequest} returns this
 */
proto.boxygen.builder.v1.FromRequest.prototype.setAs = function(value) {
  return jspb.Message.setProto3StringField(this, 10, value);
};


/**
 * repeated string ignore = 11;
 * @return {!Array<string>}
 */
proto.boxygen.builder.v1.FromRequest.prototype.getIgnoreList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 11));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.boxygen.builder.v1.FromRequest} returns this
 */
proto.boxygen.builder.v1.FromRequest.prototype.setIgnoreList = function(value) {
  return jspb.Message.setField(this, 11, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.boxygen.builder.v1.FromRequest} returns this
 */
proto.boxygen.builder.v1.FromRequest.prototype.addIgnore = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 11, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.boxygen.builder.v1.FromRequest} returns this
 */
proto.boxygen.builder.v1.FromRequest.prototype.clearIgnoreList = function() {
  return this.setIgnoreList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.boxygen.builder.v1.FromResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.boxygen.builder.v1.FromResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.boxygen.builder.v1.FromResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.boxygen.builder.v1.FromResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    container: (f = msg.getContainer()) && proto.boxygen.builder.v1.Container.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.boxygen.builder.v1.FromResponse}
 */
proto.boxygen.builder.v1.FromResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.boxygen.builder.v1.FromResponse;
  return proto.boxygen.builder.v1.FromResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.boxygen.builder.v1.FromResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.boxygen.builder.v1.FromResponse}
 */
proto.boxygen.builder.v1.FromResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.boxygen.builder.v1.Container;
      reader.readMessage(value,proto.boxygen.builder.v1.Container.deserializeBinaryFromReader);
      msg.setContainer(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.boxygen.builder.v1.FromResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.boxygen.builder.v1.FromResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.boxygen.builder.v1.FromResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.boxygen.builder.v1.FromResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getContainer();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.boxygen.builder.v1.Container.serializeBinaryToWriter
    );
  }
};


/**
 * optional Container container = 1;
 * @return {?proto.boxygen.builder.v1.Container}
 */
proto.boxygen.builder.v1.FromResponse.prototype.getContainer = function() {
  return /** @type{?proto.boxygen.builder.v1.Container} */ (
    jspb.Message.getWrapperField(this, proto.boxygen.builder.v1.Container, 1));
};


/**
 * @param {?proto.boxygen.builder.v1.Container|undefined} value
 * @return {!proto.boxygen.builder.v1.FromResponse} returns this
*/
proto.boxygen.builder.v1.FromResponse.prototype.setContainer = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.boxygen.builder.v1.FromResponse} returns this
 */
proto.boxygen.builder.v1.FromResponse.prototype.clearContainer = function() {
  return this.setContainer(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.boxygen.builder.v1.FromResponse.prototype.hasContainer = function() {
  return jspb.Message.getField(this, 1) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.boxygen.builder.v1.RunRequest.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.boxygen.builder.v1.RunRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.boxygen.builder.v1.RunRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.boxygen.builder.v1.RunRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.boxygen.builder.v1.RunRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    container: (f = msg.getContainer()) && proto.boxygen.builder.v1.Container.toObject(includeInstance, f),
    commandList: (f = jspb.Message.getRepeatedField(msg, 2)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.boxygen.builder.v1.RunRequest}
 */
proto.boxygen.builder.v1.RunRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.boxygen.builder.v1.RunRequest;
  return proto.boxygen.builder.v1.RunRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.boxygen.builder.v1.RunRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.boxygen.builder.v1.RunRequest}
 */
proto.boxygen.builder.v1.RunRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.boxygen.builder.v1.Container;
      reader.readMessage(value,proto.boxygen.builder.v1.Container.deserializeBinaryFromReader);
      msg.setContainer(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.addCommand(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.boxygen.builder.v1.RunRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.boxygen.builder.v1.RunRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.boxygen.builder.v1.RunRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.boxygen.builder.v1.RunRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getContainer();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.boxygen.builder.v1.Container.serializeBinaryToWriter
    );
  }
  f = message.getCommandList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      2,
      f
    );
  }
};


/**
 * optional Container container = 1;
 * @return {?proto.boxygen.builder.v1.Container}
 */
proto.boxygen.builder.v1.RunRequest.prototype.getContainer = function() {
  return /** @type{?proto.boxygen.builder.v1.Container} */ (
    jspb.Message.getWrapperField(this, proto.boxygen.builder.v1.Container, 1));
};


/**
 * @param {?proto.boxygen.builder.v1.Container|undefined} value
 * @return {!proto.boxygen.builder.v1.RunRequest} returns this
*/
proto.boxygen.builder.v1.RunRequest.prototype.setContainer = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.boxygen.builder.v1.RunRequest} returns this
 */
proto.boxygen.builder.v1.RunRequest.prototype.clearContainer = function() {
  return this.setContainer(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.boxygen.builder.v1.RunRequest.prototype.hasContainer = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * repeated string command = 2;
 * @return {!Array<string>}
 */
proto.boxygen.builder.v1.RunRequest.prototype.getCommandList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 2));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.boxygen.builder.v1.RunRequest} returns this
 */
proto.boxygen.builder.v1.RunRequest.prototype.setCommandList = function(value) {
  return jspb.Message.setField(this, 2, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.boxygen.builder.v1.RunRequest} returns this
 */
proto.boxygen.builder.v1.RunRequest.prototype.addCommand = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 2, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.boxygen.builder.v1.RunRequest} returns this
 */
proto.boxygen.builder.v1.RunRequest.prototype.clearCommandList = function() {
  return this.setCommandList([]);
};


goog.object.extend(exports, proto.boxygen.builder.v1);
